version: "3.5"

services:

  mule:
    image: {{ .Env.IMAGE }}
    container_name: {{ .Env.APP_ID }}
    environment:
     - MULE_EVALUATION=TRUE
    networks:
     - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mule.rule=PathPrefix(`/{{ .Env.APP_NAME }}`)"
      - "traefik.http.routers.mule.entrypoints=web"
      - "traefik.http.routers.mule.service=mule"
      - "traefik.http.services.mule.loadbalancer.server.port=8081"
      - "traefik.http.routers.mulestat.rule=PathPrefix(`/{{ .Env.APP_NAME }}-metrics`)"
      - "traefik.http.routers.mulestat.entrypoints=web"
      - "traefik.http.routers.mulestat.service=mulestat"
      - "traefik.http.services.mulestat.loadbalancer.server.port=9090"

networks:
  traefik:
    external: true
