version: "3.5"

services:

  {{ .Env.APP_NAME }}:
    image: {{ .Env.IMAGE }}
    container_name: {{ .Env.APP_ID }}
    environment:
     - MULE_EVALUATION=TRUE
    networks:
     - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.rule=PathPrefix(`/{{ .Env.APP_NAME }}`)"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.entrypoints=web"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.service={{ .Env.APP_NAME }}"
      - "traefik.http.services.{{ .Env.APP_NAME }}.loadbalancer.server.port=8081"
      - "traefik.http.routers.{{ .Env.APP_NAME }}-metrics.rule=PathPrefix(`/{{ .Env.APP_NAME }}-metrics`)"
      - "traefik.http.routers.{{ .Env.APP_NAME }}-metrics.entrypoints=web"
      - "traefik.http.routers.{{ .Env.APP_NAME }}-metrics.service={{ .Env.APP_NAME }}-metrics"
      - "traefik.http.services.{{ .Env.APP_NAME }}-metrics.loadbalancer.server.port=9090"

networks:
  traefik:
    external: true
