version: "3.5"

services:

  {{ .Env.APP_NAME }}:
    image: {{ .Env.IMAGE }}
    container_name: {{ .Env.APP_NAME }}
    environment:
     - MULE_EVALUATION=TRUE
     - MULE_MEMORY=128
    networks:
     - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.rule=Host(`{{ .Env.SERVICE_HOST }}`) && PathPrefix(`/{{ .Env.APP_NAME }}`)"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.entrypoints=websecure"
      - "traefik.http.routers.{{ .Env.APP_NAME }}.tls.certresolver=certresolver"

networks:
  traefik:
    external: true
